"""empty message

Revision ID: 0738cf0bc3ff
Revises: 
Create Date: 2022-05-13 15:37:37.824738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0738cf0bc3ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('category', sa.String(), nullable=True))
    op.drop_column('posts', 'category_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('category_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('posts', 'category')
    # ### end Alembic commands ###
